#!/bin/sh
set -e
if ! getent group pi-registrar >/dev/null; then addgroup --system pi-registrar; fi
if ! getent passwd pi-registrar >/dev/null; then adduser --system --ingroup pi-registrar --no-create-home pi-registrar; fi
install -d -o pi-registrar -g pi-registrar -m 0750 /etc/pi-registrar/client
if [ ! -e /etc/pi-registrar/client/config.ini ]; then
    install -o pi-registrar -g pi-registrar -m 0640 \
        "$DPKG_ROOT/usr/share/pi-registrar/client/config.ini" \
        /etc/pi-registrar/client/config.ini
fi
exit 0
